# Setup
title:        Aji's Blog
tagline:      Just my blog.
baseurl:      "http://blog.ajiyakin.com"

# About/contact
author:
  name:       AjiYakin
  url:        http://blog.ajiyakin.com

permalink: /:year/:month/:day/:title/

gems:
  - jemoji
