# Setup
title:        Aji's Blog
tagline:      Just my blog.
baseurl:      "http://blog.ajiyakin.com"
paginate:     1

# About/contact
author:
  name:       AjiYakin
  url:        http://blog.ajiyakin.com

permalink: date
